version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - ./:/var/www/html
    networks:
      - dev
    depends_on:
      - backend

  backend:
    build: ./swagger/
    container_name: fastapi_app
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    networks:
      - dev

networks:
  dev: